security:
    encoders:
        AppBundle\Entity\User:
            algorithm: sha512
    providers:
        employees:
            entity:
                class: AppBundle:User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            pattern:    ^/
            http_basic: ~
            provider: employees
            form_login:
                login_path: user_login
                check_path: user_login
            logout:
                path:   user_logout
                target: user_login
                invalidate_session: false

    role_hierarchy:
          ROLE_ADMIN:       [ROLE_USER, ROLE_LOGISTIC]
          ROLE_LOGISTIC:    [ROLE_USER]

    access_control:
        - { path: ^/user/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user, roles: ROLE_USER }
        - { path: ^/driver, roles: ROLE_LOGISTIC }
        - { path: ^/employee, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }