security:
    encoders:
        AppBundle\Entity\User:
            algorithm: sha512
    providers:
        employees:
            entity:
                class: AppBundle:User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            pattern:    ^/
            http_basic: ~
            provider: employees
            form_login:
                login_path: user_login
                check_path: user_login
            logout:
                path:   user_logout
                target: user_login
                invalidate_session: false
    access_control:
        - { path: ^/user/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }