# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    AppBundle\Service\DriverService:
       arguments:
          $entityManager: '@doctrine.orm.entity_manager'
          $template: '@templating'

    AppBundle\Service\CustomerService:
       arguments:
          $entityManager: '@doctrine.orm.entity_manager'
          $template: '@templating'

    AppBundle\Service\MenuService:
       arguments:
          $container: '@service_container'