employee_index:
    path:     /index
    defaults: { _controller: AppBundle:Employee:index }

employee_form:
    path:     /form
    defaults: { _controller: AppBundle:Employee:form }

employee_delete:
    path:     /delete
    defaults: { _controller: AppBundle:Employee:delete }
