user:
    resource: "user_routing.yml"
    prefix: /user
tracking:
    resource: "tracking_routing.yml"
driver:
    resource: "driver_routing.yml"
    prefix: /driver
employee:
    resource: "employee_routing.yml"
    prefix: /employee
api:
    resource: "api_routing.yml"
    prefix: /api