user_login:
    path:      /login
    defaults:  { _controller: AppBundle:User:login }
user_profile:
    path:      /profile
    defaults:  { _controller: AppBundle:User:profile }
user_logout:
    path:      /logout
    defaults:  { _controller: AppBundle:User:logout }